---
- hosts: localhost
  become: yes
  tasks:
    - name: Create ~/.gitconfig
      file:
        state: touch
        path: "/home/blod/.gitconfig"

    - name: List git config
      git_config:
        list_all: yes

    - name: Add name setting to ~/.gitconfig
      git_config:
        name: user.name
        scope: global
        value: Bohdan
        repo: "/home/blod"

    - name: Add email setting to ~/.gitconfig
      git_config:
        name: user.email
        scope: global
        value: biletskyboh@gmail.com

    - name: Add editor setting to ~/.gitconfig
      git_config:
        name: core.editor
        scope: global
        value: vim

    - name: Create folder for Vundle 
      file:
        state: directory
        path: "/home/blod/.vim/bundle/Vundle.vim"

    - name: Dowload Vundle for vim
      git:
        repo: "https://github.com/gmarik/Vundle.vim.git"
        dest: "/home/blod/.vim/bundle/Vundle.vim"
